### ISSUE TITLE
Wider base and how to cancel

### ISSUE THREAD

**Issue by stenc55** [The--Captain/pa_tuner#1]
Hi
Great tool, but...

First layer at least 3 loops? It has better chance of sticking since PA is not tuned yet and often there is oozing from nozzle while waiting for bed to stabilize after prime line is done (at least on my printer) and nozzle is empty again,

A way to cancel macro for whatever reason without need to shut down printer.
Regards
Roman

**Comment by The--Captain** [comment]
This is supposed to test/calibrate PA as fast (yet reliably) as possible, so adding things that slow down the test in order to benefit (sorry but this is true) poorly calibrated and/or configured printers is unlikely to happen.  Why are you even printing a prime line before your bed is stable?

Your second request should be directed at Kevin or another developer of Klipper.  That feature (or lack thereof) is not under my control.
